[Scia Reto](https://sciareto.org) mind map   
> __version__=`1.1`
---

# Meta
- LINK
<pre>https://github.com/raydac/meta</pre>

## Issues
> fillColor=`#FF6666`

- LINK
<pre>https://github.com/raydac/meta/issues</pre>

## Backlog
> fillColor=`#66FF66`

